### ISSUE TITLE
Version 1.22.0 of AusweisApp2 SDK updates the messages structure

### ISSUE THREAD

**Issue by AxelNennker** [telekom/SmartCredentials-SDK-android#138]
Version 1.22.0 of AusweisApp2 SDK updates the messages structure
https://www.ausweisapp.bund.de/sdk/messages.html 

This issue is about updating the eid module to incorporate these changes.

e.g. add canAllowed to message ACCESS_RIGHTS

**Comment by en-agraur** [comment]
solved in version 6.2.5
