### ISSUE TITLE
use actions/checkout@v3 instead of v2 because nodejs12 actions are deprecated

### ISSUE THREAD

**Issue by AxelNennker** [telekom/SmartCredentials-SDK-android#246]
please see: https://discourse.julialang.org/t/node-js-12-actions-deprecation-warning-on-github/88718

We use it here:
https://github.com/telekom/SmartCredentials-SDK-android/blob/develop/.github/workflows/release.yaml#L18

**Comment by enmolenici** [comment]
updated to v3
